name: Rspack Reactjs Workflow
on: push #Events that trigger workflows https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_dispatch
jobs:
  notify-start:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_CHANNEL: general
            SLACK_COLOR: "#FFFF00" # Yellow color for in-progress
            SLACK_ICON: https://a.slack-edge.com/production-standard-emoji-assets/14.0/apple-large/2b50@2x.png
            SLACK_WEBHOOK: https://hooks.slack.com/services/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
            SLACK_TITLE: Post Title
            SLACK_USERNAME: rtCamp
            SLACK_MESSAGE: 'Post Content :rocket:'
  test:
    name: Test workflow
    runs-on: ubuntu-latest #https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
      - name: Install yarn
        run: | 
            npm install --global yarn
            yarn --version
      - name: Install dependencies
        run: yarn 
      - name: Run lint
        run: yarn lint
  deploy:
    name: Deploy react app
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
      - name: Install yarn
        run: | 
            npm install --global yarn
            yarn --version
      - name: Install dependencies 
        run: yarn
      - name: Build project
        run: yarn build
      - name: Deploy
        run: echo "Deploy...."

        
        
